image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [495.53955,   0.     , 332.76363,
           0.     , 494.80888, 239.22101,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.368609, 0.140735, 0.000854, -0.000912, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [409.57639,   0.     , 336.24553,   0.     ,
           0.     , 447.21527, 238.99327,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
